package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class ChooseLevelSceneController implements Initializable {
	@FXML
	private Button _backToMainButton;
	@FXML
	private Button _beginnerButton;
	@FXML
	private Button _advancedButton;
	private MainController _mainController;
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}

	// Event Listener on Button[#_backToMainButton].onAction
	@FXML
	public void backToMainButtonClicked(ActionEvent event) {
		_mainController.goToHome();
	}
	// Event Listener on Button[#_beginnerButton].onAction
	@FXML
	public void beginnerButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_advancedButton].onAction
	@FXML
	public void advancedButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setMainController(MainController mainController) {
		_mainController = mainController;
	}
}
