package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ProgressBar;

public class RecordSceneController {
	@FXML
	private Button backToMainButton;
	@FXML
	private Label displayedNumber;
	@FXML
	private Button recordButton;
	@FXML
	private ProgressBar progressBar;

	// Event Listener on Button[#backToMainButton].onAction
	@FXML
	public void backToMain(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#recordButton].onAction
	@FXML
	public void recording(ActionEvent event) {
		// TODO Autogenerated
	}

}
