package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class ResultSceneController {
	@FXML
	private Button backToMainButton;
	@FXML
	private Label displayedCorrectness;
	@FXML
	private Button replayButton;
	@FXML
	private Label maoriText;
	@FXML
	private Button tryAgainButton;
	@FXML
	private Button nextButton;

	// Event Listener on Button[#backToMainButton].onAction
	@FXML
	public void backToMain(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#replayButton].onAction
	@FXML
	public void echo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#tryAgainButton].onAction
	@FXML
	public void tryAgain(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#nextButton].onAction
	@FXML
	public void goNext(ActionEvent event) {
		// TODO Autogenerated
	}
}
