package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class StartSceneController implements Initializable{
	@FXML
	private Button _startButton;
	private MainController _mainController;

	// Event Listener on Button[#_startButton].onAction
	@FXML
	public void startButtonClicked(ActionEvent event) {
		// TODO Autogenerated
		_mainController.showChooseLevelScene();
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}

	public void setMainController(MainController mainController) {
		// TODO Auto-generated method stub
		_mainController = mainController;
	}
}
