package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.chart.PieChart;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class SummarySceneController {
	@FXML
	private Button backToMainButton;
	@FXML
	private Label score;
	@FXML
	private PieChart pieChart;
	@FXML
	private Button goAdvancedButton;

	// Event Listener on Button[#backToMainButton].onAction
	@FXML
	public void goBackToMain(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#goAdvancedButton].onAction
	@FXML
	public void goAdvanced(ActionEvent event) {
		// TODO Autogenerated
	}
}
